kind: pipeline
type: kubernetes
name: default

trigger:
  branch:
  - main
  event:
  - push

steps:
# - name: build-docker-image
#   image: docker.io/library/docker:25.02-dind-alpine3.19
#   commands:
#   - docker build \
#     -t william/satisfactory-server:latest \
#     -t william/satisfactory-server:${DRONE_BUILD_NUMBER} \
#     -t william/satisfactory-server:${DRONE_COMMIT_SHA:0:7} \
#     ./
#     # -t williammiceli/satisfactory-server:latest \
#     # -t williammiceli/satisfactory-server:${DRONE_BUILD_NUMBER} \
#     # -t williammiceli/satisfactory-server:${DRONE_COMMIT_SHA:0:7} \
#   volumes:
#   - name: artifacts
#     path: /

- name: gitea-build-push
  image: plugins/docker
  settings:
    username:
      from_secret: GITEA_USERNAME
    password:
      from_secret: GITEA_TOKEN
    registry: https://git.williammiceli.systems
    repo: git.williammiceli.systems/william/satisfactory-server
    tags:
    - latest
    - build${DRONE_BUILD_NUMBER}
    - ${DRONE_COMMIT_SHA:0:7}
    platform: linux/amd64
  # volumes:
  # - name: artifacts
  #   path: /

# - name: docker-hub-push
#   image: docker.io/library/docker:25.02-dind-alpine3.19
#   commands:
#   - echo $DOCKER_TOKEN | docker login --username $DOCKER_USERNAME --password-stdin
#   - docker push williammiceli/satisfactory-server:latest
#   environment:
#     DOCKER_USERNAME:
#       from_secret: DOCKER_USERNAME
#     DOCKER_TOKEN:
#       from_secret: DOCKER_TOKEN
#   volumes:
#   - name: artifacts
#     path: /

# volumes:
# - name: artifacts
#   temp: {}