kind: pipeline
type: kubernetes
name: default

trigger:
  branch:
  - main
  event:
  - push

steps:
- name: build-push-gitea
  image: plugins/docker
  settings:
    username:
      from_secret: GITEA_USERNAME
    password:
      from_secret: GITEA_TOKEN
    registry: https://git.williammiceli.systems
    repo: william/docker_satisfactory-server
    tags:
    - latest
    - build${DRONE_BUILD_NUMBER}
    - ${DRONE_COMMIT_SHA:0:7}
    depends_on:
    - clone

- name: build-push-dockerhub
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_TOKEN
    registry: https://docker.io/
    repo: williammiceli/satisfactory-server
    tags:
    - latest
    - build${DRONE_BUILD_NUMBER}
    - ${DRONE_COMMIT_SHA:0:7}
    depends_on:
    - clone
