kind: pipeline
type: kubernetes
name: default

trigger:
  branch:
  - main
  event:
  - push

steps:
- name: build-push-gitea
  image: plugins/docker
  settings:
    username:
      from_secret: GITEA_USERNAME
    password:
      from_secret: GITEA_TOKEN
    registry: https://git.williammiceli.systems
    repo: git.williammiceli.systems/william/docker_satisfactory-server
    tags:
    - latest
    - build${DRONE_BUILD_NUMBER}
    - ${DRONE_COMMIT_SHA:0:7}

- name: build-push-dockerhub
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_TOKEN
    registry: https://docker.io/
    repo: williammiceli/satisfactory-server
    tags:
    - latest
    - build${DRONE_BUILD_NUMBER}
    - ${DRONE_COMMIT_SHA:0:7}

- name: finish
  image: docker.io/library/alpine:latest
  commands:
  - echo "Finished"
  depends_on:
  - build-push-gitea
  - build-push-dockerhub