name: Build and Push

on: [push]

jobs:
  get-steam-app-version:
    runs-on: ubuntu-latest
    outputs:
      APP_BUILD_ID: ${{ steps.get_app_build_id.outputs.APP_BUILD_ID }}

    steps:
      - name: Install SteamCMD Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y lib32gcc-s1 wget ca-certificates

      - name: Download and Extract SteamCMD
        run: |
          mkdir -p ~/Steam && cd ~/Steam
          wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
          tar -xvzf steamcmd_linux.tar.gz

      - name: Get APP_BUILD_ID
        id: get_app_build_id
        run: |
          cd ~/Steam
          APP_BUILD_ID=$(./steamcmd.sh +login anonymous +app_info_print 1690800 +quit | \
          awk 'BEGIN { capture = 0; } \
          /"1690800"/ { capture = 1; } \
          capture && /"branches"/ { inBranches = 1; } \
          inBranches && /"public"/ { inPublic = 1; next; } \
          inPublic && /"buildid"/ { \
              gsub(/[^0-9]/, "", $0); print; exit; \
          }')
          export GITEA_OUTPUT="${GITEA_OUTPUT:+$GITEA_OUTPUT:}APP_BUILD_ID=$APP_BUILD_ID"
          echo "APP_BUILD_ID=$APP_BUILD_ID" >> "$GITHUB_OUTPUT"
          echo "GITEA_OUTPUT=$GITEA_OUTPUT"
          echo "GITHUB_OUTPUT=$GITHUB_OUTPUT"
  
  build:
    needs: get-steam-app-version
    runs-on: ubuntu-latest
    container: 
      image: docker.io/library/ubuntu:latest
      # image: docker.io/library/docker:27.3.1-dind-rootless
      volumes:
        - /secrets/kubeconfig-buildx:/root/.kube/config
        # - /secrets/kubeconfig-buildx:/home/rootless/.kube/config
        # - /run/user/1000/docker.sock:/run/user/1000/docker.sock
        - /certs/client:/certs/client
        - /artifacts/:/artifacts/
      # options:
      #   --privileged
    env:
      KUBECONFIG: /root/.kube/config
      # KUBECONFIG: /home/rootless/.kube/config
    # container: docker.io/library/docker:27.3.1-dind-rootless
    # services:
    #   docker:
    #     image: docker.io/library/docker:27.1.2
    #     options: >
    #       --privileged
    #       -v /run/user/1000:/run/user/1000
    # env:
      # DOCKER_HOST: unix:///run/user/1000/docker.sock
      DOCKER_HOST: tcp://127.0.0.1:2376
      DOCKER_TLS_VERIFY: '1'
      DOCKER_CERT_PATH: /certs/client

    steps:

      - name: Check Kubeconfig
        run: |
          echo "HOME=$HOME"
          ls -AhlR /$HOME
          echo "done"

      - name: Install Required Build Tools
        run: |
          apt-get update

          # Install Git
          apt-get install git -y

          # Install Docker (https://docs.docker.com/engine/install/ubuntu/)
          apt-get install ca-certificates curl -y
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          chmod a+r /etc/apt/keyrings/docker.asc

          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update
          apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout Code
        run: |
          pwd
          git clone ${{github.server_url}}/${{github.repository}}.git ./
          pwd
          git checkout ${{github.sha}} --recurse-submodules
          pwd

      - name: Setup Docker Builder Container
        run: |
          docker buildx create \
            --bootstrap \
            --driver kubernetes \
            --name gitearunner_${{github.event.repository.name}}_job${{github.run_number}}- \
            --driver-opt namespace=personal-16-1,rootless=true

      - name: Check Dockerfile
        run: |
          pwd
          ls -AhlR ./

      - name: Build Docker Image
        run: |
          pwd
          docker buildx build\
            --builder gitearunner_${{github.event.repository.name}}_job${{github.run_number}}- \
            --platform=linux/amd64 \
            --tag image:latest \
            --file Dockerfile \
            --build-arg CI_BUILD_STARTED=${{github.event.commits.timestamp}} \
            --build-arg COMMIT_SHA=${{github.sha}} \
            --output type=tar,dest=- \
            . > /artifacts/${{github.event.repository.name}}_job${{github.run_number}}/image.tar
          ls -AhlR /artifacts/

      - name: Remove Docker Builder Container
        if: always()
        run: |
          docker buildx rm --force gitearunner_${{github.event.repository.name}}_job${{github.run_number}}-

  push:
    needs: build
    runs-on: ubuntu-latest
    container: 
      image: docker.io/library/docker:27.3.1-dind-rootless
      volumes:
        - /certs/client:/certs/client
        - /artifacts/:/artifacts/
    env:
      DOCKER_HOST: tcp://127.0.0.1:2376
      DOCKER_TLS_VERIFY: '1'
      DOCKER_CERT_PATH: /certs/client

    steps:

      - name: Check Artifacts
        run: |
          ls -AhlR /artifacts/

      - name: Load Image Into Docker Engine
        run: |
          docker image --input /artifacts/${{github.event.repository.name}}_job${{github.run_number}}/image.tar

      - name: CLI Login to Gitea Registry
        run: |
          echo ${{ secrets.CI_GITEA_TOKEN }} | docker login git.williammiceli.systems --username ${{ secrets.CI_GITEA_USERNAME }} --password-stdin

      - name: Login to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: git.williammiceli.systems
          username: ${{ secrets.CI_GITEA_USERNAME }}
          password: ${{ secrets.CI_GITEA_TOKEN }}

      - name: Tag and Push to Gitea Registry
        run: |
          docker tag image:latest git.williammiceli.systems/william/docker_satisfactory-server:latest
          docker tag image:latest git.williammiceli.systems/william/docker_satisfactory-server:app_build_id-${APP_BUILD_ID}
          docker tag image:latest git.williammiceli.systems/william/docker_satisfactory-server:ci_build-${{ gitea.run_number }}
          docker tag image:latest git.williammiceli.systems/william/docker_satisfactory-server:commit_sha-${{ gitea.sha::12 }}
          docker push --all-tags git.williammiceli.systems/william/docker_satisfactory-server
        env:
          APP_BUILD_ID: ${{ needs.get-steam-app-version.outputs.APP_BUILD_ID }}

      - name: CLI Login to Docker Hub Registry
        run: |
          echo ${{ secrets.CI_DOCKER_TOKEN }} | docker login git.williammiceli.systems --username ${{ secrets.CI_DOCKER_USERNAME }} --password-stdin


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_DOCKER_USERNAME }}
          password: ${{ secrets.CI_DOCKER_TOKEN }}

      - name: Tag and Push to Docker Hub
        run: |
          docker tag image:latest williammiceli/satisfactory-server:latest
          docker tag image:latest williammiceli/satisfactory-server:app_build_id-${APP_BUILD_ID}
          docker tag image:latest williammiceli/satisfactory-server:ci_build-${{ gitea.run_number }}
          docker tag image:latest williammiceli/satisfactory-server:commit_sha-${{ gitea.sha::12 }}
          docker push --all-tags williammiceli/satisfactory-server
        env:
          APP_BUILD_ID: ${{ needs.get-steam-app-version.outputs.APP_BUILD_ID }}
