name: Build and Push

on: [push]

jobs:
  get-steam-app-version:
    runs-on: ubuntu-latest
    # outputs:
    #   APP_BUILD_ID: ${{ steps.get_app_build_id.outputs.APP_BUILD_ID }}

    steps:
      - name: Install SteamCMD Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y lib32gcc-s1 wget ca-certificates

      - name: Download and Extract SteamCMD
        run: |
          mkdir -p ~/Steam && cd ~/Steam
          wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
          tar -xvzf steamcmd_linux.tar.gz

      - name: Get APP_BUILD_ID
        id: get_app_build_id
        run: |
          cd ~/Steam
          APP_BUILD_ID=$(./steamcmd.sh +login anonymous +app_info_print 1690800 +quit | \
          awk 'BEGIN { capture = 0; } \
          /"1690800"/ { capture = 1; } \
          capture && /"branches"/ { inBranches = 1; } \
          inBranches && /"public"/ { inPublic = 1; next; } \
          inPublic && /"buildid"/ { \
              gsub(/[^0-9]/, "", $0); print; exit; \
          }')
          export GITEA_OUTPUT="${GITEA_OUTPUT:+$GITEA_OUTPUT:}APP_BUILD_ID=$APP_BUILD_ID"
          echo $GITEA_OUTPUT
  
  build:
    needs: get-steam-app-version
    runs-on: ubuntu-latest
    # container: docker.io/library/docker:27.3.0-dind-rootless
    # services:
    #   docker:
    #     image: docker.io/library/docker:27.1.2
    #     options: >
    #       --privileged
    #       -v /run/user/1000:/run/user/1000
    # env:
      # DOCKER_HOST: unix:///run/user/1000/docker.sock
      # DOCKER_HOST: tcp://127.0.0.1:2376
      # DOCKER_TLS_VERIFY: '0'
      # DOCKER_CERT_PATH: /certs/client

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout Code
        run: |
          apt-get update
          apt-get install git -y
          git clone ${{github.server_url}}/${{github.repository}}.git workspace
          cd workspace
          git checkout ${{github.sha}} --recurse-submodules

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     driver: kubernetes
      #     driver-opts: |
      #       namespace=personal-16-1
      #       rootless=true
      #       serviceaccount=gitearunner-serviceaccount

      - name: Setup Docker Buildx
        run: |
          docker buildx create \
            --bootstrap \
            --driver kubernetes \
            --name kube \
            --driver-opt namespace=personal-16-1,rootless=true,serviceaccount=gitearunner-serviceaccount

      - name: Build Docker Image
        run: |
          docker buildx build\
            --builder kube \
            --platform=linux/amd64 \
            --tag image:latest \
            --file Dockerfile \
            .

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Login to Gitea Registry
        uses: docker/login-action@v3
        with:
          registry: git.williammiceli.systems
          username: ${{ secrets.CI_GITEA_USERNAME }}
          password: ${{ secrets.CI_GITEA_TOKEN }}

      - name: Tag and Push to Gitea Registry
        run: |
          docker tag image:latest git.williammiceli.systems/william/docker_satisfactory-server:latest
          docker tag image:latest git.williammiceli.systems/william/docker_satisfactory-server:app_build_id-${APP_BUILD_ID}
          docker tag image:latest git.williammiceli.systems/william/docker_satisfactory-server:ci_build-${{ gitea.run_number }}
          docker tag image:latest git.williammiceli.systems/william/docker_satisfactory-server:commit_sha-${{ gitea.sha::12 }}
          docker push --all-tags git.williammiceli.systems/william/docker_satisfactory-server
        env:
          APP_BUILD_ID: ${{ steps.get_app_build_id.outputs.APP_BUILD_ID }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_DOCKER_USERNAME }}
          password: ${{ secrets.CI_DOCKER_TOKEN }}

      - name: Tag and Push to Docker Hub
        run: |
          docker tag image:latest williammiceli/satisfactory-server:latest
          docker tag image:latest williammiceli/satisfactory-server:app_build_id-${APP_BUILD_ID}
          docker tag image:latest williammiceli/satisfactory-server:ci_build-${{ gitea.run_number }}
          docker tag image:latest williammiceli/satisfactory-server:commit_sha-${{ gitea.sha::12 }}
          docker push --all-tags williammiceli/satisfactory-server
        env:
          APP_BUILD_ID: ${{ steps.get_app_build_id.outputs.APP_BUILD_ID }}
